version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.12.13
    - 7.13.0
  - dependency-name: webpack
    versions:
    - 5.21.2
    - 5.28.0
    - 5.30.0
    - 5.31.2
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.19.0
    - 4.20.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.14
  - dependency-name: webpack-dev-server
    versions:
    - 4.0.0-beta.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.12
  - dependency-name: copy-webpack-plugin
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: stylelint
    versions:
    - 13.12.0
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
  - dependency-name: core-js
    versions:
    - 3.9.1
